ASSIGNMENT 6
ANANTPREET KAUR
1024170112


In [2]:
#QUES1
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])


corrected_temperature = temperature + 2

print("Corrected temperatures:", corrected_temperature)


fahrenheit = (9/5) * corrected_temperature + 32

print("Temperature in Fahrenheit:", fahrenheit)


greater_than_32 = corrected_temperature[corrected_temperature > 32]

print("Readings greater than 32°C:", greater_than_32)


count = np.sum(corrected_temperature > 32)

print("Number of readings greater than 32°C:", count)

Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperature in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings greater than 32°C: 5


In [3]:
#QUES2
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])


total_steps = np.sum(steps)
print("Total steps:", total_steps)


mean_steps = np.mean(steps)
print("Mean steps:", mean_steps)


maximum = np.max(steps)
minimum = np.min(steps)

print("Maximum steps:", maximum)
print("Minimum steps:", minimum)


day_total = np.sum(steps, axis=0)
print("Total steps for each day:", day_total)


user_total = np.sum(steps, axis=1)
print("Total steps for each user:", user_total)


max_position = np.unravel_index(np.argmax(steps), steps.shape)

print("Position of maximum steps:", max_position)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum steps: (np.int64(3), np.int64(2))


In [4]:
#QUES3
import numpy as np


original = np.array([1, 2, 3, 4, 5, 6])


subset = original[1:5]

print("Subset:", subset)


subset[0] = 999

print("Original after modifying subset:", original)
print("Subset:", subset)


copied = original[1:5].copy()

copied[0] = 500

print("Original after modifying copied array:", original)
print("Copied array:", copied)


matrix = np.arange(1, 13).reshape(3, 4)

print("3 x 4 Matrix:")
print(matrix)




print("First row:", matrix[0])


print("Last row:", matrix[-1])


print("Second column:", matrix[:, 1])


print("Rows 1-2 and columns 2-3:")
print(matrix[0:2, 1:3])


flat_array = matrix.flatten()
ravel_array = matrix.ravel()

print("Flatten:", flat_array)
print("Ravel:", ravel_array)


ravel_array[0] = 100

print("After modifying ravel:")
print("Original matrix:")
print(matrix)
print("Ravel:", ravel_array)


flat_array[1] = 200

print("After modifying flatten:")
print("Original matrix:")
print(matrix)
print("Flatten:", flat_array)


print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Subset: [2 3 4 5]
Original after modifying subset: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original after modifying copied array: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]
3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[2 3]
 [6 7]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
After modifying ravel:
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Ravel: [100   2   3   4   5   6   7   8   9  10  11  12]
After modifying flatten:
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flatten: [  1 200   3   4   5   6   7   8   9  10  11  12]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [5]:
#QUES4
import numpy as np


X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])


y = np.array([40, 65, 30, 85])


print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)


XT = X.T

print("Transpose of X:")
print(XT)


XTX = XT @ X

print("X.T @ X:")
print(XTX)


XTX_inverse = np.linalg.inv(XTX)

print("Inverse of X.T @ X:")
print(XTX_inverse)


beta = XTX_inverse @ XT @ y

print("OLS coefficients:")
print(beta)


print("\nCoefficients:")
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])


new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("Predicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2
Transpose of X:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
OLS coefficients:
[-0.15921454  0.14083853 10.06302242]

Coefficients:
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587
Predicted assistance score: 75.27862544779117
