# Assignment 5
Anantpreet kaur
1024170112

In [ ]:
from scipy.stats import binom

In [1]:
# Question 1
import numpy as np

array = np.array([10, 20, 30, 40, 50])

print("Original Array:", array)

print("After adding 2:", array + 2)
print("After multiplying by 3:", array * 3)
print("After dividing by 2:", array / 2)

Original Array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [2]:
# Question 2
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print("Original Array:", arr)
print("Reversed Array:", arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print()

print("Most frequent value:", most_frequent)
print("Indices:", indices)
print()

y = np.array([1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print("Most frequent value:", most_frequent)
print("Indices:", indices)

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]

Most frequent value: 1
Indices: [0 5 7 8 9]

Most frequent value: 3
Indices: [3 7 8]


In [3]:
# Question 3
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


print("1st row, 2nd column:", arr[0, 1])


print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [4]:
# Question 4
import numpy as np

Anantpreet = np.linspace(10, 100, 25)

print("Array:")
print(Anantpreet)

print("Dimensions:", Anantpreet.ndim)
print("Shape:", Anantpreet.shape)
print("Total elements:", Anantpreet.size)
print("Data type:", Anantpreet.dtype)
print("Total bytes:", Anantpreet.nbytes)


transposed = Anantpreet.reshape(1, 25)

print("Transpose using reshape:")
print(transposed)

# Transpose using T
print("Transpose using T:")
print(Anantpreet.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [5]:
# Question 5
import numpy as np


ucs420_Anantpreet = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_Anantpreet)
print()


print("Mean:", np.mean(ucs420_Anantpreet))


print("Median:", np.median(ucs420_Anantpreet))


print("Maximum:", np.max(ucs420_Anantpreet))


print("Minimum:", np.min(ucs420_Anantpreet))


print("Unique elements:", np.unique(ucs420_Anantpreet))


ucs420_Anantpreet = ucs420_Anantpreet.reshape(4, 3)

print("\nAfter Reshaping to 4 x 3:")
print(ucs420_Anantpreet)

# Resize to 2 rows and 3 columns
resized_ucs420_Anantpreet = np.resize(ucs420_Anantpreet, (2, 3))

print("\nAfter Resizing to 2 x 3:")
print(resized_ucs420_Anantpreet)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

After Reshaping to 4 x 3:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

After Resizing to 2 x 3:
[[10 20 30]
 [40 50 60]]
